apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: p257rdnd5-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:3bfecbfb859dca13d12775b4fac3ab9fecc8ec42@sha256:f83570e7d00b642c2377e2f1eae30afdf2cb1667896e5e360f7ff314d28855f2
          name: container-image
