apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: p257rdnd5-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/p257rdnd5-java-springboot-gitops